/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.Signos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Collections;
import java.util.Random;
import sun.security.util.Length;

/**
 *
 * @author Bruno-PC
 */
public class Signos extends javax.swing.JFrame {

    /**
     * Creates new form Signos
     */
    public Signos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtdian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtmesn = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtanon = new javax.swing.JTextField();
        txtsexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seja Bem-Vindo !! – Somos especialistas em prever o futuro!!!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setText("Nome:");

        jLabel2.setText("Sexo:");

        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("1 - Feminino.  2 - Masculino");

        jLabel4.setText("Dia de Nascimento:");

        jButton1.setText("VERIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/Signos/Imagem/Ascendente-1.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setText("Mês de Nascimento:");

        jLabel10.setText("Ano de Nascimento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmesn, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txtdian)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtanon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmesn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtanon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja limpar?", "Limpar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) { // mostra uma caixa de confirmação para limpar os campos de digitação
            // comando para limpar os campos
            txtnome.setText("");
            txtsexo.setText("");
            txtdian.setText("");
            txtanon.setText("");
            txtmesn.setText("");
            txtnome.requestFocus();
            JOptionPane.showMessageDialog(null, "Todos os campos foram limpados com sucesso!"); // se os campos forem limpos, mostra em JOptionPane
        } else {
            JOptionPane.showMessageDialog(null, "Cancelado!"); // caso não forem limpados, irá aparecer isso
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // declaração de variaveis
        int dian, mesn, anon, sexo, idade = 0, diaA, mesA, anoA, numerosorte = 0, escolha = 0, Pnome;
        String nome, signo = "", sexo1, nomewidth;
        Calendar hoje = Calendar.getInstance();
        diaA = hoje.get(Calendar.DATE);
        mesA = hoje.get(Calendar.MONTH) + 1;
        anoA = hoje.get(Calendar.YEAR);
        nome = txtnome.getText();
        Pnome = txtnome.getText().length();
        dian = Integer.parseInt(txtdian.getText());
        mesn = Integer.parseInt(txtmesn.getText());
        anon = Integer.parseInt(txtanon.getText());
        sexo = Integer.parseInt(txtsexo.getText());
        if (Pnome >= 8) {
            // calculo da idade
            numerosorte = (int) 1 + (int) (Math.random() * 99); // sorteia um numero entre 1 e 99
            ArrayList lista = new ArrayList(); // cria lista de palavras
            lista.add("Vemelho");
            lista.add("Preto");
            lista.add("Branco");
            lista.add("Laranja");
            lista.add("Verde");
            lista.add("Azul");
            lista.add("Amarelo");
            lista.add("Rosa");
            lista.add("Violeta");
            lista.add("Marrom");
            lista.add("Cinza");
            lista.add("Prata");
            Collections.shuffle(lista);
            for (int i = 0; i < 1; i++) {
                escolha = (int) Math.random() * lista.size(); //randomiza as palavras criadas acima
            }
            lista.remove(escolha);
            if (anon >= 1900 && anon <= 2016) {//diz que só pode ser digitado anos entre 1900 e o ano atual
                if (mesn > 0 && mesn < 13 && dian > 0 && dian < 32) {
                    if ((mesn == 2 && dian <= 28) || (mesn == 4 && dian <= 30) || (mesn == 6 && dian <= 30) || (mesn == 9 && dian <= 30) || (mesn == 11 && dian <= 30) || (mesn == 1 && dian <= 31) || (mesn == 3 && dian <= 31) || (mesn == 5 && dian <= 31) || (mesn == 7 && dian <= 31) || (mesn == 8 && dian <= 31) || (mesn == 10 && dian <= 31) || (mesn == 12 && dian <= 31)) {
                        if ((mesA > mesn && diaA <= dian) || (mesA > mesn && diaA > dian) || (mesA == mesn && diaA >= dian)) {
                            idade = anoA - anon;
                        }
                        if ((mesA < mesn && diaA <= dian) || (mesA < mesn && diaA > dian) || (mesA == mesn && diaA < dian)) {
                            idade = anoA - anon - 1;
                        }
                        if ((mesn == 12) && (dian >= 22) && (dian <= 31)
                                || (mesn == 1) && (dian >= 1) && (dian <= 20)) {
                            signo = "Capricórnio";
                        } else if ((mesn == 1) && (dian >= 21) && (dian <= 31)
                                || (mesn == 2) && (dian >= 1) && (dian <= 19)) {
                            signo = "Aquário";
                        } else if ((mesn == 2) && (dian >= 20) && (dian <= 29)
                                || (mesn == 3) && (dian >= 1) && (dian <= 20)) {
                            signo = "Peixes";
                        } else if ((mesn == 3) && (dian >= 21) && (dian <= 31)
                                || (mesn == 4) && (dian >= 1) && (dian <= 20)) {
                            signo = "Áries";
                        } else if ((mesn == 4) && (dian >= 21) && (dian <= 30)
                                || (mesn == 5) && (dian >= 1) && (dian <= 20)) {
                            signo = "Touro";
                        } else if ((mesn == 5) && (dian >= 21) && (dian <= 31)
                                || (mesn == 6) && (dian >= 1) && (dian <= 20)) {
                            signo = "Gêmeos";
                        } else if ((mesn == 6) && (dian >= 21) && (dian <= 30)
                                || (mesn == 7) && (dian >= 1) && (dian <= 21)) {
                            signo = "Cancêr";
                        } else if ((mesn == 7) && (dian >= 22) && (dian <= 31)
                                || (mesn == 8) && (dian >= 1) && (dian <= 22)) {
                            signo = "Leão";
                        } else if ((mesn == 8) && (dian >= 23) && (dian <= 31)
                                || (mesn == 9) && (dian >= 1) && (dian <= 22)) {
                            signo = "Virgem";
                        } else if ((mesn == 9) && (dian >= 23) && (dian <= 30)
                                || (mesn == 10) && (dian >= 1) && (dian <= 22)) {
                            signo = "Libra";
                        } else if ((mesn == 10) && (dian >= 23) && (dian <= 31)
                                || (mesn == 11) && (dian >= 1) && (dian <= 21)) {
                            signo = "Escorpião";
                        } else if ((mesn == 11) && (dian >= 22) && (dian <= 30)
                                || (mesn == 12) && (dian >= 1) && (dian <= 21)) {
                            signo = "Sagitário";
                        }
                        switch (sexo) {
                            case 1:
                                JOptionPane.showMessageDialog(null, "Sra." + nome + "\nNascida no dia " + dian + "-" + mesn + "-" + anon + ".\nSeu signo é: " + signo + ".\nVocê tem: " + idade + " anos de idade" + "\nSeu número da sorte é: " + numerosorte + "\nSua cor da sorte é: " + lista.get(escolha));
                                break;
                            case 2:
                                JOptionPane.showMessageDialog(null, "Sr." + nome + "\nNascido no dia " + dian + "-" + mesn + "-" + anon + ".\nSeu signo é: " + signo + ".\nVocê tem: " + idade + " anos de idade" + "\nSeu número da sorte é: " + numerosorte + "\nSua cor da sorte é: " + lista.get(escolha));
                                break;
                            default:
                                JOptionPane.showMessageDialog(null, "ERRO!" + "\nDigite 1 para Feminino." + "\nDigite 2 para Masculino");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "ERRO!" + "\nFevereiro : 28 dias." + "\nAbril, Junho, Setembro e Novembro: 30 dias");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "ERRO!" + "\nDigite um mês ou dia válido" + "\n Só são permitidos dias entre 1 e 31, exceto para mesês como Fevereiro(02), Abril(04), Junho(06), Setembro(0 u9), Novembro(11)!" + "\nSó são permitidos mesês entre 1 e 12!");
                }
            } else if (anoA < anon) {
                JOptionPane.showMessageDialog(null, "Por acaso você veio do futuro? ");
            } else {
                JOptionPane.showMessageDialog(null, "Só são permitidos anos entre 1900 e " + anoA);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Legal se o seu nome fosse verdadeiro!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Sobre frame = new Sobre();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtanon;
    private javax.swing.JTextField txtdian;
    private javax.swing.JTextField txtmesn;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsexo;
    // End of variables declaration//GEN-END:variables
}
